import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// Import components
import Navbar from "@/Components/Navbar";
import Footer from "@/Components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Doc House",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="./logo.svg" />
      </head>
      <body className={inter.className}>
        <div className="container mx-auto px-5">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
